name: test1
on:
  workflow_dispatch:
    inputs:
      git_ref:
        type: string

jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
      - id: test1
        shell: bash
        run: |
          LONG_BRANCH_NAME=${{ inputs.git_ref }}
          echo "LONG_BRANCH_NAME: ${LONG_BRANCH_NAME}"
          SHORT_BRANCH=${LONG_BRANCH_NAME#refs/heads/}
          echo "short_branch_name=$SHORT_BRANCH" >> $GITHUB_ENV

      - id: test2
        shell: bash
        run: |
          echo "${{ steps.test1.outputs.short_branch_name }}"
    