name: test1
on:
  workflow_dispatch:
    inputs:
      git_ref:
        type: string

jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
      - id: test1
        name: test 1 step
        shell: bash
        run: |
          echo "${{ format('vendoring-{0}', github.ref_name) }}"

    