name: test1
on:
  workflow_dispatch:
    inputs:
      git_ref:
        type: string

jobs:

  prepare-status:
    runs-on: ubuntu-latest
    steps:
      - id: test1
        shell: bash
        run: |
          LONG_BRANCH_NAME=${{ inputs.git_ref }}
          echo "LONG_BRANCH_NAME: ${LONG_BRANCH_NAME}"
          SHORT_BRANCH=${LONG_BRANCH_NAME#refs/heads/}
          echo "SHORT_BRANCH: ${SHORT_BRANCH}"
    