name: test1
on:
  workflow_dispatch:
    inputs:
      git_ref:
        type: string

jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
      - id: test1
        name: test 1 step
        shell: bash
        run: |
          LONG_BRANCH_NAME=${{ inputs.git_ref }}
          echo "LONG_BRANCH_NAME: ${LONG_BRANCH_NAME}"
          echo "short_branch_name=${LONG_BRANCH_NAME#refs/heads/}" >> "${GITHUB_OUTPUT}"

      - id: test2
        name: test 2 step
        shell: bash
        run: |
          echo "${{ steps.test1.outputs.short_branch_name }}"
    